### PR TITLE
use broadcasting instead of my_min/max

### PR DESCRIPTION
**Pull request by Wikunia**
While looking at the models you wrote I found out that you're using `my_min` and `my_max` to make sure that a vector of variables is bounded. This can be easily expressed in Julia using broadcasting.

### CODE REVIEW

**Comment by hakank** [comment]
Thanks for the PR, Ole! 

You have certainly a good point about this. I'll merge it soon.

However, my intuition would be to write the constraint in the other way around, i.e. for `max` use the `>=` operator and for `min` use `<=`. I.e.
```
   @constraint(model, max_x .>= x) # max
   @constraint(model, min_x .<= x) # min
```

Do you have a reason - technical or stylistic - to prefer that the array is always on the LHS of the operator?

**Comment by Wikunia** [comment]
That's just the way I do it 😂 no idea why I somewhat find it easier to read.

**Comment by hakank** [comment]
Interesting. Well, I'll stick to my intuition about this. And sorry if I happen to change your nice variant. :-)

**Comment by Wikunia** [comment]
You have way more experience with modelling than myself so please change it the way you like it.
BTW v0.6.1 will be out tmr which allows you to use `>` and `<` so no need for `<= ... -1` anymore :wink:

**Comment by hakank** [comment]
Thanks for your kind words. I'm looking forward to the new version!

**Pull request merged**
